author: Wilfried Woivré
name: Wilfried Woivré
description: Quelques recettes plus ou moins simple et rapides

title: Wilfried Woivré
subtitle: Quelques recettes plus ou moins simple et rapides

url: "http://recettes.woivre.fr"

baseurl: ""

github: ""

twitter_username: ""
linkedin_username: ""

gaaccount: 

comments: false

isso: ''
disqs: ''

urls:
    - text: Home
      url: /
      target: _self

permalink: '/:year/:month/:title'

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      permalink: '/blog/:year/:month/:title'
      title: 'Wilfried Woivré & Cooking - :title'

paginate: 12

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

plugins: 
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

lang: fr

exclude: ['utils', 'README.md', 'LICENSE']